config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
  resources :apps, only: [:new]
  resources :rel_apps, only: [:create, :destroy]
  resources :friendcodes
end

app/models/app.rb
class App < ApplicationRecord
  validates :trackid, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :image_url, presence: true, length: { maximum: 255 }
  
  has_many :rel_apps
  has_many :users, through: :rel_apps
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendcode.rb
class Friendcode < ApplicationRecord
  belongs_to :user
  belongs_to :app
end

app/models/rel_app.rb
class RelApp < ApplicationRecord
  belongs_to :user
  belongs_to :app
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :rel_apps
  has_many :apps, through: :rel_apps
  has_many :friendcodes
  
  scope :get_by_name, ->(name){where("name like ?","%#{name}%")}
  
  def have(app)
    self.rel_apps.find_or_create_by(app_id: app.id)
  end
  
  def unhave(app)
    rel = self.rel_apps.find_by(app_id: app.id)
    rel.destroy
  end
  
  def have?(app)
    self.apps.exists?(trackid: app.trackid)
  end
  
  def input_friendcode(app,friendcode)
    self.friendcodes.find_or_create_by(app_id: app.id, friendcode: friendcode)
  end
  
  def update_friendcode(app,friendcode)
    app = self.friendcodes.find_by(app_id: app.id)
    app.update(friendcode: friendcode)
  end
  
  def friendcode?(app)
    self.friendcodes.exists?(app_id: app.id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

  def read(result)
    trackid = result['trackId']
    name = result['trackName']
    image_url = result['artworkUrl100']

    return {
      name: name,
      image_url: image_url,
      trackid: trackid
    }
  end
  
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :require_user_logged_in

  def new
    @apps = []

    @keyword = params[:keyword]
    if @keyword
      results = ITunesSearchAPI.search(:term => @keyword, :country => "JP", :media => "software").select{ |app| app["primaryGenreName"] == "Games" }

      results.each do |result|
        # 扱い易いように Item としてインスタンスを作成する（保存はしない）
        app = App.find_or_initialize_by(read(result))
        @apps << app
      end
    end
  end

end

app/controllers/friendcodes_controller.rb
class FriendcodesController < ApplicationController
  def show
    @friendcode = current_user.friendcodes.first
  end
  
  def new
  end
  
  def create
    @friendcode = []
    @app = App.find(params[:app_id])
    current_user.input_friendcode(@app,params[:friendcode])
    flash[:success] = 'フレンドコードを登録しました'
    redirect_to :back
  end

  def update
    @app = App.find(params[:app_id])
    current_user.update_friendcode(@app,params[:friendcode][:friendcode])
    flash[:success] = 'フレンドコードを変更しました'
    redirect_to :back
  end
  
end

app/controllers/rel_apps_controller.rb
class RelAppsController < ApplicationController
  def create
    @app = App.find_or_initialize_by(trackid: params[:trackid])
    
    unless @app.persisted?
      results = ITunesSearchAPI.lookup(:id => @app.trackid, :country => 'jp')
      @app = App.new(read(results))
      @app.save
    end
    current_user.have(@app)
    redirect_to user_path(current_user)
  end

  def destroy
    @app = App.find(params[:app_id])
    current_user.unhave(@app)
    redirect_to user_path(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def index
    @users = User.all
    @keyword = params[:keyword]
    if @keyword
      @users = @users.get_by_name params[:keyword]
    end
  end
  
  def show
    @user = User.find(params[:id])
    @apps = @user.apps
    @friendcodes = @user.friendcodes
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/apps/_apps.html.erb
<% if apps %>
  <div class="row">
    <% apps.each do |app| %>
      <div class="app">
        <div class="col-md-2 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= app.image_url %>" alt="">
            </div>
            <div class="panel-body text-center">
              <p class="app-title"><%= app.name %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/apps/new.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(new_app_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: "キーワードを入力", size: 40 %>
        </div>
        <%= submit_tag '商品を検索', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'apps', apps: @apps %>

app/views/friendcodes/_edit.html.erb
<% if apps %>
  <div class="row">
    <% apps.each do |app| %>
      <div class="app">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= app.image_url %>" alt="">
            </div>
            <div class="panel-body text-center app-title">
              <p class="app-title"><%= app.name %></p>
            </div>
            <ul class="friendcode-edit list-group">
              <li class="list-group-item text-center">
                <% if current_user.friendcode?(app) %>
                  <% friendcodes.each do |friendcode| %>
                    <% if friendcode.app_id == app.id %>
                      <%= form_for(friendcode) do |f| %>
                        <%= hidden_field_tag :app_id, app.id %>
                        <%= f.text_field :friendcode, class: "friendcode-edit form-group", value: friendcode.friendcode %>
                        <%= f.submit %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% else %>
                  <%= form_tag(friendcodes_path) do %>
                    <%= hidden_field_tag :app_id, app.id %>
                    <%= text_field_tag :friendcode%>
                    <%= submit_tag %>
                  <% end %>
                <% end %>
              </li>
              <li class="list-group-item text-center"><%= render 'rel_apps/have_button', app: app %></li>
              </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<div class="addapp text-center">
  <%= link_to new_app_path do %>
    <div class="btn btn-primary">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      アプリを追加
    </div>
  <% end %>
</div>

app/views/friendcodes/_show.html.erb
<% if apps %>
  <div class="row">
    <% apps.each do |app| %>
      <div class="app">
        <div class="col-md-2 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= app.image_url %>" alt="">
            </div>
            <div class="panel-body text-center app-title">
              <p class="app-title"><%= app.name %></p>
            </div>
            <ul class="list-group">
              <li class="list-group-item text-center">
                <% if user.friendcode?(app) %>
                  <% friendcodes.each do |friendcode| %>
                    <% if friendcode.app_id == app.id %>
                      <%= friendcode.friendcode %>
                    <% end %>
                  <% end %>
                <% else %>
                  未登録
                <% end %>      
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2017 Sociage.hub</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-left nav-title" href="/">Sociage.hub</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
            <li class="nav-usersearch">
              <div class="nav text-center">
                <%= form_tag(users_path, method: :get, class: 'form-inline') do %>
                  <div class="form-group">
                    <%= text_field_tag :keyword, @keyword, class: 'form-control input-xs', placeholder: "ユーザー名を入力", size: 20 %>
                  </div>
                  <%= submit_tag '検索', class: 'btn btn-success btn-sm' %>
                <% end %>
              </div>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'マイページ', user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Monolist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/rel_apps/_have_button.html.erb
<% if current_user.have?(app) %>
  <%= form_tag(rel_app_path(app.id), method: :delete) do %>
    <%= hidden_field_tag :app_id, app.id %>
    <%= submit_tag '削除', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(rel_apps_path) do %>
    <%= hidden_field_tag :trackid, app.trackid %>
    <%= submit_tag '追加', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>Sociage.hub</h1>
    </div>
  </div>
<% end %>

app/views/users/_haveapps.html.erb
<% if apps %>
  <div class="row">
    <% apps.each do |app| %>
      <div class="app">
        <div class="col-md-2 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= app.image_url %>" alt="">
            </div>
            <div class="panel-body text-center app-title">
              <p class="app-title"><%= app.name %></p>
            </div>
            <ul class="list-group">
                <li class="list-group-item text-center">
                  <% if current_user.friendcode?(app) %>
                    <% @friendcodes.each do |friendcode| %>
                      <% if friendcode.app_id == app.id %>
                        <%= form_for(friendcode) do |f| %>
                          <%= hidden_field_tag :app_id, app.id %>
                          <%= f.text_field :friendcode, class: "form-group", value: friendcode.friendcode %>
                          <%= f.submit %>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% else %>
                    <%= form_tag(friendcodes_path) do %>
                      <%= hidden_field_tag :app_id, app.id %>
                      <%= text_field_tag :friendcode%>
                      <%= submit_tag %>
                    <% end %>
                  <% end %>
                </li>
            </ul>
            <div class="buttons text-center">
                <p><%= render 'rel_apps/have_button', app: app %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/_user.html.erb
<% if users %>
  <div class="row">
    <% users.each do |user| %>
      <div class="user">
        <div class="col-md-2 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= gravatar_url(user) %>" alt="">
            </div>
            <div class="panel-body text-center">
              <p class="app-title"><%= link_to user.name, user_path(user) %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(users_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: "ユーザー名を入力", size: 40 %>
        </div>
        <%= submit_tag '検索', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'users/user', users: @users %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="user-profile">
    <div class="icon text-center">
      <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
    </div>
    <div class="name text-center">
      <h1><%= @user.name %></h1>
    </div>
    <div>
      <% if current_user.id == @user.id %>
        <%= render 'friendcodes/edit',user: @user, apps: @apps, friendcodes: @friendcodes %>
      <% else %>
        <%= render 'friendcodes/show',user: @user, apps: @apps, friendcodes: @friendcodes %>
      <% end %>
    </div>
  </div>

</div>